[package]
name = "nbsysrc"
version = "0.1.0"
authors = ["Ron Georgia <rong1611@gmail.com>"]
edition = "2018"

[dependencies]
clap = "4.2.1"
nix = '0.26.2'
# os_type = { path = "/home/rgeorgia/workspace/os_type" }
