#!/bin/sh
#
# $NetBSD: hal.sh,v 1.3 2015/09/25 16:26:16 richard Exp $
#
# PROVIDE: hal
# REQUIRE: DAEMON dbus
# KEYWORD: shutdown

. /etc/rc.subr

name="hal"
rcvar=$name
command="/usr/pkg/sbin/hald"
start_precmd=hal_prestart

hal_prestart() {
	dir="/var/run/hald"
	if test ! -d $dir; then
		/bin/mkdir -p $dir
		/bin/chmod 0755 $dir
		/usr/sbin/chown haldaemon:operator $dir
	fi
	/bin/chmod 0755 "/var/cache"
}

load_rc_config $name
run_rc_command "$1"
