#!/bin/sh
#
# $NetBSD: winbindd.sh,v 1.6 2015/01/23 08:09:37 obache Exp $
#
# PROVIDE: winbindd
# REQUIRE: DAEMON

. /etc/rc.subr

name="winbindd"
rcvar=$name
command="/usr/pkg/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/usr/pkg/etc/samba/smb.conf"
extra_commands="reload"

load_rc_config $name
run_rc_command "$1"
